### ISSUE TITLE
About modal (Eug)

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-products-design-kit#15]
[Pattern docs](https://pages.github.ibm.com/cdai-design/pal/patterns/about-modal/usage)

**Need modal update on core library**

- [ ] Anatomy: overlay, Pictogram/Icon, Product name, Version number, Links (optional), General text (optional), Trademark and copyright info, Powered by logos (optional), Close button.
- [ ] Option to show vertical scrolling.

Surfacing quote from Laura Marshall (code/design mismatch):

> This component is a weird one, and one of the more problematic ones to match, as the design guidance and code have clear mismatches. The guidance is so old that no one is really around to understand the original intent. With that in mind though, definetly want to match code as much as possible, and this change makes sense for sure :) 

> But also, any changes that feel odd, I'd definetly reach out to Elysia Hwang to understand some of the code reasoning!

**Comment by elycheea** [comment]
Most teams likely have this implemented already but there are some visual changes between Carbon 10 and 11 so could be relevant to v11 migrations. Probably also relevant for acquisition teams.
