### ISSUE TITLE
Figma optimization: Generate API key

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-products-design-kit#21]
[Pattern docs on old site](https://pages.github.ibm.com/cdai-design/pal/patterns/generating-api-key/usage)
[Component docs on new site](https://pages.github.ibm.com/carbon/ibm-products/components/api-key-modal/usage/)

**Review existing component for:**
- v11 token usage
- sub components pulling from v10 Carbon or C4IP kits
- any variants we can get rid of or condense (Rich to advise)

**Need modal update on core library**

- [ ] Options for `modal` size
- [ ] Options for stage in flow
- [ ] Review changes with Rich

**Comment by aubrey-oneal** [comment]
A few notes to discuss:

Generate default small 
- AI slug is floating out in a weird place (applies to other variants)
- Is the AI background supposed to show the gradient on the buttons? (Applies to other variants)
![Image](https://github.com/user-attachments/assets/384475d6-63d8-4518-9179-9e0734fe1780)

Generate API Key Bases

- Loading is using v11 but there is a warning that the variant in use is not included in the component
![Image](https://github.com/user-attachments/assets/194e0dd6-9d08-4f72-80ad-cb1d545c9123)

- Where is the copy button base used? Is this necessary to keep?
![Image](https://github.com/user-attachments/assets/cd8e45df-1696-49d9-b002-25753cc55da5)
