### ISSUE TITLE
Figma optimization: Keyboard shortcut guidance

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-products-design-kit#24]
[Pattern docs](https://pages.github.ibm.com/cdai-design/pal/patterns/keyboard-shortcut-guidance/usage)

- [x] Option for on-screen indicator.
- [x] Keyboard shortcut modal
     - [x]  Anatomy: Modal title ("Keyboard shortcuts"), Categories, Groups, Command, Note
- [x] In Figma the 'Running' state is listed as 'Active'. Is this the same in code?

**Comment by elycheea** [comment]
I wanted to close this but maybe the keyboard shortcut indicator would still be nice. Going to mark it as low since we haven’t had any requests/questions about this one.
