### ISSUE TITLE
Figma optimization: Save

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-products-design-kit#28]
[Pattern docs](https://pages.github.ibm.com/cdai-design/pal/patterns/saving/usage)

- [x] Manual saving
- [x] Manual saving multiple states (saving vs saved)
- [x] Auto saving

**Comment by ljcarot** [comment]
@RichKummer This now a component and has been renamed to 'Save' as you probably know.  https://pages.github.ibm.com/carbon/ibm-products/components/save/usage/.  Is this slated to be worked in the next sprint or is it on the path to be ready as part of Beta-> Stable.

**Comment by RichKummer** [comment]
@ljcarot Yes, those updates to category and name are already reflected in the kit (just not the story here). It's set to be worked on this sprint by the community.
