### ISSUE TITLE
Color picker (To be deprecated)

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-products-design-kit#3]
[Component docs](https://pages.github.ibm.com/cdai-design/pal/components/color-picker/usage/)

- [ ] Anatomy: color palette dropdown (optional), color palette, Add color (optional), custom color picker (optional)
- [ ] Variants: Simple, custom, Color palette picker
- [ ] Has a fixed width of `256px`.
- [ ] Proper label alignment.

**Comment by elycheea** [comment]
I’d also recommend closing this one since we’re replacing color picker with the style picker in time and I’m not sure this was in kit (but definitely not code).
