### ISSUE TITLE
Figma kit new: Condition builder (sentence)

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-products-design-kit#4]
[2023 design](https://www.figma.com/file/LBvWjDAhCQxoQ67eCbN8PU/Condition-Builder-component---Visual-Design---Sep-2023?type=design&node-id=0%3A1&mode=design&t=DVP8j1su6IHNpp11-1)

[Background github story #349](https://github.ibm.com/CDAI-design/pal/issues/349)

[Implementation tracking](https://github.com/carbon-design-system/ibm-products/issues/4577)

Dependency on [Figma mapping](https://github.com/orgs/carbon-design-system/projects/65/views/1?filterQuery=figma&pane=issue&itemId=61578774) for condition builder

**Comment by My-Money29** [comment]
Adding the data structure options available for the out-of-the-box Properties.

[Condition Builder - Data structure.md](https://github.com/carbon-design-system/carbon-for-products-design-kit/files/15260137/Condition.Builder.-.Data.structure.md)
