### ISSUE TITLE
Figma AI styling: Productive card

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-products-design-kit#52]
We need to add AI styling options for this component or pattern to the Figma kit. 

These additions should be part of the Figma components itself, and should not create additional variants. Ensure that the AI layer can expand responsively to cover the background area. The AI label should also be positioned to behave responsively based on the design.

See [tearsheet](https://www.figma.com/design/0F9dKH2abAd7gSfvnacfWf/(v11-Beta)-IBM-Products-%E2%80%93-Carbon-Design-System?node-id=9837-338109&t=OR8A2dsdxIEz9gpf-1) as an example:
<img width="1182" alt="Screenshot 2024-09-27 at 12 11 09 PM" src="https://github.com/user-attachments/assets/32d3ba05-bc38-4eaf-b432-f5e584852ae8">

```[tasklist]
### Add if relevant
- [x] Add AI label that appears with AI presence
- [x] Add AI border that appears with AI presence
- [x] Add AI layer that appears with AI presence
- [x] Add AI shadow that appears with AI presence
- [x] Publish kit update
```

**Comment by elycheea** [comment]
@RichKummer Moving this to sprint 30 since it was untagged. But feel free to move it back to 29 if it just wasn’t captured correctly.
