### ISSUE TITLE
Menu and combo buttons

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-products-design-kit#8]
[Pattern doc](https://pages.github.ibm.com/cdai-design/pal/components/button-guidance/menu-and-combo-buttons/)

**Menu button**
- [ ] Open and closed state
- [ ] Three height options: default, field, and small.
- [ ] Three different button types: primary, tertiary, and ghost

**Combo button**
- [ ] Open and closed state
- [ ] Only available as primary buttons.
- [ ] Three height options: default, field, and small
- [ ] min-width of `160px`

**Modifiers for both button types**
- [ ] Disabled states for menu items
- [ ] Divider lines
- [ ] Optional danger state for menu item

**Comment by elycheea** [comment]
Hmm, even our guidance recommends using the Carbon menu and combo buttons so maybe we can either close or lower the priority? 🤔
